name: cbj_smart_device
description: Creating CyBear Jinni Smart Devices
version: 1.0.1
homepage: https://cybearjinni.com


environment:
  sdk: ^3.1.5

dependencies:
  cbj_integrations_controller:
    # git: https://github.com/CyBear-Jinni/cbj_integrations_controller.git
    path: ../cbj_integrations_controller
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.1
  # Convert enum to string
  enum_to_string: ^2.0.1
  # Allow returning more than one type of object
  equatable: ^2.0.5
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.6.4
  # A high performance, open source, general RPC framework that puts mobile and HTTP/2 first.
  grpc: ^3.2.4
  # Convenient code generator for get_it
  injectable: ^2.3.2  # Does not work on my armhf32, can be lack of ram https://TypeAdaptergithub.com/dart-lang/pub/issues/2347
  # Checks for an internet connection by opening a socket
  internet_connection_checker: ^1.0.0+1
  # Extremely fast, easy to use, and fully async NoSQL database.
  isar: ^3.1.0+1
  # Collection of lint rules for Dart and Flutter projects
  lint: ^2.1.2
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.0.2+1
  # Process run helpers for Linux/Win/Mac.
  process_run: ^0.13.2
  # Extends the capabilities of Dart Streams and StreamControllers.
  rxdart: ^0.27.7
  # Provides parse, inspect, and manipulate stack traces
  stack_trace: ^1.11.0
  uuid: ^4.1.0

dev_dependencies:
  build_runner:

  # A generator for injectable library
  injectable_generator: ^2.4.1  # Does not work on my armhf32, can be lack of ram https://github.com/dart-lang/pub/issues/2347

  # Code generator for the Isar Database. Finds classes annotated with @Collection.
  isar_generator: ^3.1.0+1
  # Library for mocks
  mockito: ^5.4.2
  test: ^1.24.9
